import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="grid place-items-center min-h-screen">
        <article className="flex flex-col justify-center items-center">
          <h1>Welcome to the Engine room of</h1>
          <h1>BUET ME&apos;20</h1>
        </article>
      </section>
    </div>
  );
};

export default Home;
